import os
from dotenv import load_dotenv
from enum import StrEnum

load_dotenv(".env")

class EnvironmentKeys(StrEnum):
    AZURE_OPENAI_GPT_4O_ENDPOINT = "AZURE_OPENAI_GPT_4O_ENDPOINT"
    AZURE_OPENAI_GPT_4O_API_KEY = "AZURE_OPENAI_GPT_4O_API_KEY"
    AZURE_OPENAI_GPT_4O_API_VERSION = "AZURE_OPENAI_GPT_4O_API_VERSION"
    AZURE_OPENAI_GPT_4O_DEPLOYMENT_NAME = "AZURE_OPENAI_GPT_4O_DEPLOYMENT_NAME"
    AZURE_OPENAI_GPT_4O_MODEL_NAME = "AZURE_OPENAI_GPT_4O_MODEL_NAME"
    AZURE_OPENAI_GPT_4O_MODEL_OUTPUT_MAX_TOKENS = "AZURE_OPENAI_GPT_4O_4O_MODEL_OUTPUT_MAX_TOKENS"
    AZURE_OPENAI_SMALL_EMBEDDING_ENDPOINT = "AZURE_OPENAI_GPT_4O_ENDPOINT"
    AZURE_OPENAI_SMALL_EMBEDDING_API_KEY = "AZURE_OPENAI_GPT_4O_API_KEY"
    AZURE_OPENAI_SMALL_EMBEDDING_API_VERSION = "AZURE_OPENAI_GPT_4O_API_VERSION"
    AZURE_OPENAI_SMALL_EMBEDDING_DEPLOYMENT_NAME = "AZURE_OPENAI_GPT_4O_DEPLOYMENT_NAME"
    AZURE_OPENAI_SMALL_EMBEDDING_MODEL_NAME = "AZURE_OPENAI_GPT_4O_MODEL_NAME"
    TEA_SUPPORT_DATA_PATH = "TEA_SUPPORT_DATA_PATH"

def env_setting(key:EnvironmentKeys):
    return os.environ[key.value]